#!/usr/bin/env bash
# Builds a self-contained habits-pwa/ directory for deployment to habits.kisushotto.com
set -e

OUT="habits-pwa"

mkdir -p "$OUT/icons" "$OUT/images"

# App files
cp habits/index.html  "$OUT/index.html"
cp habits/style.css   "$OUT/style.css"
cp habits/main.js     "$OUT/main.js"
cp habits/api.js      "$OUT/api.js"

# Adjust manifest path in index.html (subdominio uses /manifest.json at root)
sed -i 's|href="/manifests/habits.json"|href="/manifest.json"|g' "$OUT/index.html"

# Manifest at root
cp public/manifests/habits.json "$OUT/manifest.json"

# Service worker
cp habits/push.js "$OUT/push.js"

# Service worker — habits-specific with push notification support
cat > "$OUT/sw.js" << 'SWEOF'
const CACHE = 'ks-habits-v2';

self.addEventListener('install', () => { self.skipWaiting(); });

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('push', e => {
  let data = {};
  try { data = e.data ? e.data.json() : {}; } catch { data = {}; }
  const title = data.title || 'Habitos';
  const body  = data.body  || '';
  e.waitUntil(self.registration.showNotification(title, {
    body,
    tag: 'habits-reminder',
    icon: '/images/habits-favicon.svg',
    badge: '/icons/habits-192.png',
    data: { url: '/' },
  }));
});

self.addEventListener('notificationclick', e => {
  e.notification.close();
  e.waitUntil(clients.openWindow(e.notification?.data?.url || '/'));
});

self.addEventListener('fetch', e => {
  if (e.request.mode === 'navigate') {
    e.respondWith(fetch(e.request).catch(() => caches.match('/')));
    return;
  }
  const url = new URL(e.request.url);
  if (url.origin === self.location.origin &&
      (url.pathname.endsWith('.js') || url.pathname.endsWith('.css'))) {
    e.respondWith(
      fetch(e.request).then(res => {
        const clone = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, clone));
        return res;
      }).catch(() => caches.match(e.request))
    );
    return;
  }
  e.respondWith(caches.match(e.request).then(cached => cached || fetch(e.request)));
});
SWEOF

# Cache headers
cat > "$OUT/_headers" << 'HEADERS'
/sw.js
  Cache-Control: no-store

/manifest.json
  Cache-Control: public, max-age=86400

/.well-known/assetlinks.json
  Cache-Control: public, max-age=3600
  Content-Type: application/json

/*.js
  Cache-Control: no-cache

/*.css
  Cache-Control: no-cache
HEADERS

# Icons
cp public/icons/habits-192.png "$OUT/icons/habits-192.png"
cp public/icons/habits-512.png "$OUT/icons/habits-512.png"

# Favicon SVG
cp public/images/habits-favicon.svg "$OUT/images/habits-favicon.svg"

# Digital Asset Links for TWA — only if generated by build-habits-apk.sh
if [ -f "public/.well-known/habits-assetlinks.json" ]; then
  mkdir -p "$OUT/.well-known"
  cp "public/.well-known/habits-assetlinks.json" "$OUT/.well-known/assetlinks.json"
fi

echo "habits-pwa/ built OK"
