#!/usr/bin/env bash
# Builds a self-contained notes-pwa/ directory for deployment to notes.kisushotto.com
set -e

OUT="notes-pwa"

mkdir -p "$OUT/icons" "$OUT/images"

# App files
cp notes/index.html  "$OUT/index.html"
cp notes/style.css   "$OUT/style.css"
cp notes/main.js     "$OUT/main.js"
cp notes/api.js      "$OUT/api.js"
cp notes/auth.js     "$OUT/auth.js"
cp notes/idb.js      "$OUT/idb.js"
cp notes/sync.js     "$OUT/sync.js"
cp notes/push.js     "$OUT/push.js"
cp notes/recorder.js "$OUT/recorder.js"

# Adjust manifest path in index.html (subdominio uses /manifest.json at root)
sed -i 's|href="/manifests/notes.json"|href="/manifest.json"|g' "$OUT/index.html"

# Inject short commit hash + build timestamp so the watermark is unique per build
SHORT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "local")
BUILD_TS=$(date -u +%H%M%S)
sed -i "s|BUILD_HASH|${SHORT_SHA}-${BUILD_TS}|g" "$OUT/index.html"

# Manifest at root, with start_url/scope rewritten to "/"
cp public/manifests/notes.json "$OUT/manifest.json"
sed -i 's|"start_url": "/notes/"|"start_url": "/"|; s|"scope": "/notes/"|"scope": "/"|' "$OUT/manifest.json"

# Service worker — notes-specific, network-first for JS/CSS so updates are picked up immediately
cat > "$OUT/sw.js" << 'SWEOF'
const CACHE = 'ks-notes-v11';

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
      .then(async () => {
        // Force reload all open tabs so they get fresh JS immediately
        const all = await self.clients.matchAll({ type: 'window' });
        all.forEach(c => c.navigate(c.url));
      })
  );
});

self.addEventListener('push', e => {
  let data = {};
  try { data = e.data ? e.data.json() : {}; } catch { data = { title: 'Recordatorio', body: 'Tienes una nota' }; }
  const title = data.title || 'Notas';
  const body  = data.body  || '';
  const tag   = data.noteId ? `notes-${data.noteId}` : 'notes';
  const url   = data.noteId ? `/?note=${encodeURIComponent(data.noteId)}` : '/';
  e.waitUntil(self.registration.showNotification(title, {
    body, tag,
    icon: '/images/notes-icon.svg',
    badge: '/icons/notes-192.png',
    data: { url },
  }));
});

self.addEventListener('notificationclick', e => {
  e.notification.close();
  e.waitUntil(clients.openWindow(e.notification?.data?.url || '/'));
});

self.addEventListener('sync', e => {
  if (e.tag === 'notes-flush') {
    e.waitUntil((async () => {
      const cs = await self.clients.matchAll({ includeUncontrolled: true });
      for (const c of cs) c.postMessage({ type: 'flush-queue' });
    })());
  }
});

self.addEventListener('fetch', e => {
  if (e.request.mode === 'navigate') {
    e.respondWith(fetch(e.request).catch(() => caches.match('/')));
    return;
  }
  const url = new URL(e.request.url);
  // Network-first for app files so deploys take effect immediately
  if (url.origin === self.location.origin &&
      (url.pathname.endsWith('.js') || url.pathname.endsWith('.css'))) {
    e.respondWith(
      fetch(e.request).then(res => {
        const clone = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, clone));
        return res;
      }).catch(() => caches.match(e.request))
    );
    return;
  }
  e.respondWith(
    caches.match(e.request).then(cached => cached || fetch(e.request))
  );
});
SWEOF

# Icons
cp public/icons/notes-192.png "$OUT/icons/notes-192.png"
cp public/icons/notes-512.png "$OUT/icons/notes-512.png"

# Favicon + logo SVG
cp public/images/notes-favicon.svg "$OUT/images/notes-favicon.svg"
cp public/images/notes-logo.svg    "$OUT/images/notes-logo.svg"
cp public/images/notes-icon.svg    "$OUT/images/notes-icon.svg"

# Cache headers — always regenerated
cat > "$OUT/_headers" << 'HEADERS'
/sw.js
  Cache-Control: no-store

/manifest.json
  Cache-Control: public, max-age=86400

/.well-known/assetlinks.json
  Cache-Control: public, max-age=3600
  Content-Type: application/json

/*.js
  Cache-Control: no-cache

/*.css
  Cache-Control: no-cache
HEADERS

# Digital Asset Links for TWA — only if generated by build-notes-apk.sh
if [ -f "public/.well-known/assetlinks.json" ]; then
  mkdir -p "$OUT/.well-known"
  cp "public/.well-known/assetlinks.json" "$OUT/.well-known/assetlinks.json"
fi

echo "notes-pwa/ built OK"
