#!/usr/bin/env bash
# Builds a self-contained p2p-pwa/ directory for deployment to p2p.kisushotto.com
set -e

OUT="p2p-pwa"
# Version unica por build: invalida la cache del SW en cada deploy
BUILD_ID="$(date +%s)"

mkdir -p "$OUT/icons" "$OUT/images"

# App files
cp p2p-monitor/index.html         "$OUT/index.html"
cp p2p-monitor/decision-engine.js "$OUT/decision-engine.js"
cp p2p-monitor/decision-journal.js "$OUT/decision-journal.js"

# Rewrite manifest path: subdomain serves manifest.json at root
sed -i 's|href="/manifests/p2p-monitor.json"|href="/manifest.json"|g' "$OUT/index.html"

# Manifest at root (scope/start_url remapped from /p2p-monitor/ to /)
node -e "
const fs = require('fs');
const m = JSON.parse(fs.readFileSync('public/manifests/p2p-monitor.json','utf8'));
m.start_url = '/';
m.scope = '/';
m.background_color = '#000000';
m.theme_color = '#000000';
m.icons = [
  { src: '/images/p2p-favicon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
  { src: '/icons/p2p-192.png', sizes: '192x192', type: 'image/png', purpose: 'any maskable' },
  { src: '/icons/p2p-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' }
];
fs.writeFileSync('$OUT/manifest.json', JSON.stringify(m, null, 2));
"

# Service worker — minimal cache + navigation fallback
cat > "$OUT/sw.js" << 'SWEOF'
const CACHE = 'ks-p2p-v1';

self.addEventListener('install', () => { self.skipWaiting(); });

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
      .then(() => self.clients.matchAll({ type: 'window' }))
      .then(clients => clients.forEach(c => c.postMessage({ type: 'SW_UPDATED' })))
  );
});

self.addEventListener('push', e => {
  let data = {};
  try { data = e.data ? e.data.json() : {}; } catch { data = {}; }
  const title = data.title || 'P2P Monitor';
  const body  = data.body  || '';
  e.waitUntil(self.registration.showNotification(title, {
    body,
    tag: 'p2p-alert',
    icon: '/icons/p2p-192.png',
    badge: '/icons/p2p-192.png',
    data: { url: '/' },
  }));
});

self.addEventListener('notificationclick', e => {
  e.notification.close();
  e.waitUntil(clients.openWindow(e.notification?.data?.url || '/'));
});

self.addEventListener('fetch', e => {
  if (e.request.mode === 'navigate') {
    e.respondWith(fetch(e.request).catch(() => caches.match('/')));
    return;
  }
  const url = new URL(e.request.url);
  if (url.origin === self.location.origin &&
      (url.pathname.endsWith('.js') || url.pathname.endsWith('.css'))) {
    e.respondWith(
      fetch(e.request).then(res => {
        const clone = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, clone));
        return res;
      }).catch(() => caches.match(e.request))
    );
    return;
  }
  e.respondWith(caches.match(e.request).then(cached => cached || fetch(e.request)));
});
SWEOF

# Sello de version unico para forzar actualizacion del SW en cada deploy
sed -i "s/ks-p2p-v1/ks-p2p-${BUILD_ID}/" "$OUT/sw.js"

# Cache headers
cat > "$OUT/_headers" << 'HEADERS'
/sw.js
  Cache-Control: no-store

/manifest.json
  Cache-Control: public, max-age=86400

/.well-known/assetlinks.json
  Cache-Control: public, max-age=3600
  Content-Type: application/json

/*.js
  Cache-Control: no-cache

/*.css
  Cache-Control: no-cache
HEADERS

# Favicon (paths stay /images/p2p-favicon.svg)
cp public/images/p2p-favicon.svg "$OUT/images/p2p-favicon.svg"

# Launcher PNG icons (rasterized from the SVG strokes onto a black canvas)
node -e "
const sharp = require('sharp');
const svg = require('fs').readFileSync('public/images/p2p-icon.svg');
const bg = { r:0, g:0, b:0, alpha:1 };

async function makeIcon(dst, canvas) {
  const iconSize = Math.round(canvas * 0.82);
  const iconBuf = await sharp(svg).resize(iconSize, iconSize).png().toBuffer();
  return sharp({ create: { width: canvas, height: canvas, channels: 4, background: bg } })
    .composite([{ input: iconBuf, gravity: 'center' }])
    .png()
    .toFile(dst);
}

Promise.all([
  makeIcon('$OUT/icons/p2p-192.png', 192),
  makeIcon('$OUT/icons/p2p-512.png', 512),
]).then(() => console.log('PWA icons OK')).catch(e => { console.error(e); process.exit(1); });
"

# Digital Asset Links for TWA — only if generated by build-p2p-apk.sh
if [ -f "public/.well-known/p2p-assetlinks.json" ]; then
  mkdir -p "$OUT/.well-known"
  cp "public/.well-known/p2p-assetlinks.json" "$OUT/.well-known/assetlinks.json"
fi

echo "p2p-pwa/ built OK"
